### PR TITLE
Adds icons for CIC Geospatial Data Discovery Project institutions

### PR DESCRIPTION
**Pull request by krdyke**
Minnesota is already taken care of (thanks by the way!). This PR adds icons for the following institutions:

+ Illinois
+ Iowa
+ Maryland
+ Michigan
+ Michigan State
+ Penn State
+ Purdue
+ Wisconsin

They're not all the same size, but they're all square and look good via the preview. Let me know anything that needs adjusting.

### CODE REVIEW

**Comment by mejackreed** [comment]
Thanks for pulling this together. Did you run `fontcustom compile` locally to update everything automatically? When I run on your branch it modifies various files and moves things around.

I can't preview the new fonts you added.. They are showing up like this for me:

screen shot 2016-06-13 at 2 56 37 pm

**Comment by krdyke** [comment]
Yikes. Yeah I used fontcustom compile. I used watch mainly as I was
tweaking stuff. Should I need to include anything besides the SVGs?

FWIW I just cloned myself (?)  into a new folder and to get the new ones to
display I had to use fontcustom compile graphics, rather than just fontcustom
compile

**Comment by mejackreed** [comment]
Ok. I was about to get things working, but I think there are a couple of issues still:

 - [ ] an update to icons should update most of these files. after running `fontcustom compile` locally I see a status change like this:

```
	modified:   .fontcustom-manifest.json
	modified:   app/assets/fonts/geoblacklight-icons.eot
	modified:   app/assets/fonts/geoblacklight-icons.svg
	modified:   app/assets/fonts/geoblacklight-icons.ttf
	modified:   app/assets/fonts/geoblacklight-icons.woff
	modified:   app/assets/stylesheets/_geoblacklight-icons-rails.scss
	modified:   app/assets/stylesheets/_geoblacklight-icons.scss
	modified:   docs/styleguide/geoblacklight-icons-preview.html
```

Running the `fontcustom compile` command should automatically update all of the files.

 - [ ] Michigan "M" appears off center. Should the "M" be darkened with no box?
 - [ ] Maryland text may be really hard to read. Is there a version of this that would work better for the icon?
 - [ ] Penn State icon text might be really difficult to read too. Maybe the alternate version? (shield darkened?) 
screen shot 2016-06-13 at 4 08 19 pm
 - [ ] Wisconsin can this fit the whole size of the svg canvas (max height)
 - [ ] Purdue can this fit the whole size of the svg canvas (max width)

**Comment by krdyke** [comment]
alright here's another shot. 

- [x]  Missing files. **I had only committed the SVGs and not the generated files (`geoblacklight-icons.*`, etc) . They're in there now.**
- [x] Michigan "M" appears off center. Should the "M" be darkened with no box? **Centered and inverted**
- [x]  Maryland text may be really hard to read. Is there a version of this that would work better for the icon? **Replaced with a simpler turtle shell representation. Fear the Turtle!**
- [x]  Penn State icon text might be really difficult to read too. Maybe the alternate version? (shield darkened?) **Removed text and inverted colors to darken shield**
- [x]  Wisconsin can this fit the whole size of the svg canvas (max height) **eliminated white space to match canvas exactly to shape**
- [x]  Purdue can this fit the whole size of the svg canvas (max width) **eliminated white space to match canvas exactly to shape**

WRT Wisc and Purdue, their aspect ratios are not ideal for a square icon, so I'm not sure what else to do in those cases.

**Comment by mejackreed** [comment]
No need to make the logo square, just max to the width/height of whichever is longer. Definitely want to keep the aspect ratio the same.

**Comment by krdyke** [comment]
Ok that's how I interpreted it! Purdue and Wisconsin should both be maxed out.

**Comment by mejackreed** [comment]
Awesome. Looks great. Do you mind squashing the commits down into one?

**Comment by krdyke** [comment]
Alrighty all squashed up.

**Pull request merged**
